receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319
      grpc:
        endpoint: 0.0.0.0:4320

processors:
  batch:
    timeout: 1s
  resource:
    attributes:
      - key: test.key
        value: "gateway"
        action: insert
  tail_sampling:
    decision_wait: 2s
    num_traces: 100
    expected_new_traces_per_sec: 1
    policies:
      [
          # {
          #   name: test-policy-1,
          #   type: status_code,
          #   status_code: {status_codes: [ERROR]}
          # },
          # {
          #   name: test-policy-2,
          #   type: latency,
          #   latency: {threshold_ms: 1500}
          # },
      ]
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    namespace: promexample
    const_labels:
      label1: value1

  logging:
    loglevel: info

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch, resource]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]